# Generated by Django 4.1 on 2023-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=None, upload_to='category_images'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
